### ISSUE TITLE
Does this work in 1.16?

### ISSUE THREAD

**Issue by valzzu** [enayet123/BackupOnEventPlugin#2]
As the title says, does this work in 1.16? I would like to use this if it works.

**Comment by enayet123** [comment]
Hey @valzzu, I've tested with 1.16.1 and it's working just fine. Are you having issues with the latest version of the plugin?

**Comment by valzzu** [comment]
I didn't try cuz i wanted to be sure that it worked Before downloading it, thanks!

**Comment by enayet123** [comment]
Okay great, I'm closing this then
